apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: team4application

  source:
    repoURL: https://github.com/ramannkhanna2/argocd-repo.git
    targetRevision: main
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: springbootmongo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
